require("dotenv").config(); // Załaduj zmienne środowiskowe
const axios = require("axios");
const xlsx = require("xlsx");

// Twój klucz API Google z pliku .env
const API_KEY = process.env.API_KEY;

// Endpointy Google Places API
const TEXT_SEARCH_URL = `https://maps.googleapis.com/maps/api/place/textsearch/json`;
const DETAILS_URL = `https://maps.googleapis.com/maps/api/place/details/json`;

// Lista największych miast w Polsce
const cities = [
  "Warszawa",
  "Kraków",
  "Łódź",
  "Wrocław",
  "Poznań",
  "Gdańsk",
  "Szczecin",
  "Bydgoszcz",
  "Lublin",
  "Katowice",
  "Białystok",
  "Gdynia",
  "Częstochowa",
  "Radom",
  "Toruń",
  "Sosnowiec",
  "Kielce",
  "Gliwice",
  "Zabrze",
  "Bytom",
  "Olsztyn",
  "Rzeszów",
  "Bielsko-Biała",
  "Ruda Śląska",
  "Rybnik",
  "Tychy",
  "Dąbrowa Górnicza",
  "Opole",
  "Elbląg",
  "Płock",
  "Wałbrzych",
  "Gorzów Wielkopolski",
  "Włocławek",
  "Zielona Góra",
  "Tarnów",
  "Chorzów",
  "Koszalin",
  "Legnica",
  "Grudziądz",
  "Słupsk",
  "Jaworzno",
  "Jastrzębie-Zdrój",
  "Nowy Sącz",
  "Jelenia Góra",
  "Konin",
  "Piła",
  "Lubin",
  "Inowrocław",
  "Siemianowice Śląskie",
  "Mysłowice",
  "Ostrołęka",
  "Zamość",
  "Kędzierzyn-Koźle",
  "Piotrków Trybunalski",
  "Zgierz",
  "Leszno",
  "Siedlce",
  "Biała Podlaska",
  "Pruszków",
  "Tomaszów Mazowiecki",
  "Otwock",
  "Przemyśl",
  "Świdnica",
  "Tarnowskie Góry",
  "Stargard",
  "Pabianice",
  "Ełk",
  "Wejherowo",
  "Chełm",
  "Olkusz",
  "Mielec",
  "Krotoszyn",
  "Świnoujście",
  "Kutno",
  "Ciechanów",
  "Gniezno",
  "Ostrów Wielkopolski",
  "Skarżysko-Kamienna",
  "Piaseczno",
  "Głogów",
  "Oświęcim",
  "Suwałki",
  "Nowa Sól",
  "Bartoszyce",
  "Kołobrzeg",
  "Żory",
  "Zawiercie",
  "Świebodzin",
  "Bochnia",
  "Bielawa",
  "Wołomin",
  "Tarnobrzeg",
  "Knurów",
  "Jarosław",
  "Łomża",
  "Krosno",
  "Chrzanów",
  "Świętochłowice",
  "Nowy Tomyśl",
  "Sandomierz",
  "Łowicz",
  "Kwidzyn",
  "Brzeg",
  "Lubartów",
  "Kraśnik",
  "Dębica",
  "Mińsk Mazowiecki",
  "Żuromin",
  "Augustów",
  "Września",
  "Ostrzeszów",
  "Myślenice",
  "Kościerzyna",
  "Gorlice",
  "Wadowice",
  "Nowy Dwór Mazowiecki",
  "Sochaczew",
  "Puławy",
  "Zgorzelec",
  "Wągrowiec",
  "Chojnice",
  "Śrem",
  "Żnin",
  "Lubaczów",
  "Limanowa",
  "Sieradz",
  "Środa Wielkopolska",
  "Zakopane",
  "Kolno",
  "Busko-Zdrój",
  "Rawa Mazowiecka",
  "Nysa",
  "Szczytno",
  "Środa Śląska",
  "Dzierżoniów",
  "Złotoryja",
  "Koło",
  "Oława",
  "Pisz",
  "Hajnówka",
  "Sulechów",
  "Łask",
  "Pleszew",
  "Kamienna Góra",
  "Oborniki",
  "Prudnik",
  "Lubań",
  "Czarnków",
  "Gostyń",
  "Złotów",
  "Wschowa",
  "Mogilno",
  "Biskupiec",
  "Szczecinek",
  "Międzyrzecz",
  "Gryfice",
  "Wałcz",
  "Świdnik",
  "Łańcut",
  "Radomsko",
  "Pszczyna",
  "Cieszyn",
  "Sanok",
  "Lesko",
  "Wyszków",
  "Sokołów Podlaski",
  "Parczew",
  "Krasnystaw",
  "Radzyń Podlaski",
  "Bytów",
  "Lębork",
  "Puck",
  "Dziwnów",
  "Ustka",
  "Darłowo",
  "Kamień Pomorski",
  "Barlinek",
  "Kartuzy",
  "Łobez",
  "Drawsko Pomorskie",
  "Strzelce Opolskie",
  "Krapkowice",
  "Prudnik",
  "Ząbkowice Śląskie",
  "Gryfów Śląski",
  "Świebodzice",
  "Polkowice",
  "Kłodzko",
  "Lubsko",
  "Żagań",
  "Wschowa",
  "Kostrzyn nad Odrą",
  "Trzebiatów",
  "Międzyzdroje",
  "Świnoujście",
  "Środa Wielkopolska",
  "Gostynin",
  "Turek",
  "Łowicz",
  "Łask",
  "Rawa Mazowiecka",
  "Kozienice",
  "Pionki",
  "Siedlce",
  "Biała Podlaska",
  "Węgrów",
  "Garwolin",
  "Żyrardów",
  "Piastów",
  "Legionowo",
  "Pruszków",
  "Otwock",
  "Mińsk Mazowiecki",
  "Radzymin",
  "Pułtusk",
  "Ostrołęka",
  "Maków Mazowiecki",
  "Ostrołęka",
  "Przasnysz",
  "Mława",
  "Ciechanów",
  "Nowe Miasto Lubawskie",
  "Iława",
  "Ostróda",
  "Mrągowo",
  "Giżycko",
  "Gołdap",
  "Ełk",
  "Olecko",
  "Suwałki",
  "Augustów",
  "Łomża",
  "Zambrów",
  "Bielsk Podlaski",
  "Hajnówka",
  "Sokółka",
  "Białystok",
  "Mońki",
  "Grajewo",
  "Kolno",
  "Sejny",
  "Siemiatycze",
  "Wysokie Mazowieckie",
  "Łapy",
  "Węgorzewo",
  "Ruciane-Nida",
  "Pisz",
  "Orzysz",
  "Kętrzyn",
  "Bartoszyce",
  "Lidzbark Warmiński",
  "Dobre Miasto",
  "Biskupiec",
  "Szczytno",
  "Nidzica",
  "Działdowo",
  "Nowe Miasto Lubawskie",
  "Ostróda",
  "Iława",
  "Morąg",
  "Elbląg",
  "Pasłęk",
  "Braniewo",
  "Pieniężno",
  "Orneta",
  "Frombork",
  "Tolkmicko",
  "Grudziądz",
  "Świecie",
  "Chełmno",
  "Toruń",
  "Inowrocław",
  "Włocławek",
  "Ciechocinek",
  "Aleksandrów Kujawski",
  "Rypin",
  "Brodnica",
  "Golub-Dobrzyń",
  "Nakło nad Notecią",
  "Żnin",
  "Mogilno",
  "Janowiec Wielkopolski",
  "Bydgoszcz",
  "Solec Kujawski",
  "Koronowo",
  "Tuchola",
  "Chojnice",
  "Czersk",
  "Sępólno Krajeńskie",
  "Więcbork",
  "Wąbrzeźno",
  "Barcin",
  "Żnin",
  "Szubin",
  "Nakło nad Notecią",
  "Inowrocław",
  "Kruszwica",
  "Janikowo",
  "Barcin",
  "Aleksandrów Kujawski",
  "Ciechocinek",
  "Włocławek",
  "Rypin",
  "Brodnica",
  "Golub-Dobrzyń",
  "Toruń",
  "Chełmża",
  "Kowal",
  "Lipno",
  "Tłuchowo",
  "Sierpc",
  "Płock",
  "Gąbin",
  "Gostynin",
  "Kutno",
  "Żychlin",
  "Łowicz",
  "Skierniewice",
  "Żyrardów",
  "Piastów",
  "Pruszków",
  "Otwock",
  "Karczew",
  "Sulejówek",
  "Mińsk Mazowiecki",
  "Siedlce",
  "Łosice",
  "Garwolin",
  "Biała Podlaska",
  "Węgrów",
  "Radzymin",
  "Pułtusk",
  "Ostrołęka",
  "Maków Mazowiecki",
  "Przasnysz",
  "Mława",
  "Ciechanów",
  "Płońsk",
  "Nasielsk",
  "Nowe Miasto",
  "Nowy Dwór Mazowiecki",
  "Sochaczew",
  "Grodzisk Mazowiecki",
  "Żyrardów",
  "Błonie",
  "Piastów",
  "Legionowo",
  "Marki",
  "Ząbki",
  "Wołomin",
  "Kobyłka",
  "Radzymin",
  "Mińsk Mazowiecki",
  "Sulejówek",
  "Otwock",
  "Karczew",
  "Pilawa",
  "Garwolin",
  "Łaskarzew",
  "Siedlce",
  "Łosice",
  "Biała Podlaska",
  "Janów Podlaski",
  "Terespol",
  "Międzyrzec Podlaski",
  "Radzyń Podlaski",
  "Parczew",
  "Lubartów",
  "Lublin",
  "Świdnik",
  "Piaski",
  "Bychawa",
  "Bełżyce",
  "Opole Lubelskie",
  "Poniatowa",
  "Puławy",
  "Nałęczów",
  "Kazimierz Dolny",
  "Dęblin",
  "Ryki",
  "Łęczna",
  "Włodawa",
  "Chełm",
  "Rejowiec Fabryczny",
  "Krasnystaw",
  "Zamość",
  "Tomaszów Lubelski",
  "Hrubieszów",
  "Biłgoraj",
  "Janów Lubelski",
  "Modliborzyce",
  "Lublin",
  "Świdnik",
  "Bychawa",
  "Łęczna",
  "Lubartów",
  "Kraśnik",
  "Opole Lubelskie",
  "Puławy",
  "Nałęczów",
  "Kazimierz Dolny",
  "Dęblin",
  "Ryki",
  "Włodawa",
  "Chełm",
  "Rejowiec Fabryczny",
  "Krasnystaw",
  "Zamość",
  "Tomaszów Lubelski",
  "Hrubieszów",
  "Biłgoraj",
  "Janów Lubelski",
  "Rzeszów",
  "Przemyśl",
  "Jarosław",
  "Lubaczów",
  "Łańcut",
  "Leżajsk",
  "Nisko",
  "Stalowa Wola",
  "Tarnobrzeg",
  "Nowa Dęba",
  "Mielec",
  "Kolbuszowa",
  "Strzyżów",
  "Jasło",
  "Krosno",
  "Sanok",
  "Lesko",
  "Ustrzyki Dolne",
  "Brzozów",
  "Dynów",
  "Błażowa",
  "Boguchwała",
  "Tyczyn",
  "Głogów Małopolski",
  "Sokołów Małopolski",
  "Rzeszów",
  "Przeworsk",
  "Kańczuga",
  "Jarosław",
  "Radymno",
  "Przemyśl",
  "Ustrzyki Dolne",
  "Sanok",
  "Brzozów",
  "Jasło",
  "Krosno",
  "Rymanów",
  "Dukla",
  "Strzyżów",
  "Kolbuszowa",
  "Mielec",
  "Tarnobrzeg",
  "Nowa Dęba",
  "Stalowa Wola",
  "Nisko",
  "Leżajsk",
  "Łańcut",
  "Lubaczów",
  "Cieszanów",
  "Narol",
  "Biłgoraj",
  "Janów Lubelski",
  "Modliborzyce",
  "Zamość",
  "Tomaszów Lubelski",
  "Hrubieszów",
  "Krasnystaw",
  "Chełm",
  "Włodawa",
  "Dęblin",
  "Kazimierz Dolny",
  "Puławy",
  "Nałęczów",
  "Opole Lubelskie",
  "Bełżyce",
  "Lublin",
  "Świdnik",
  "Bychawa",
  "Łęczna",
  "Lubartów",
  "Parczew",
  "Radzyń Podlaski",
];

// Funkcja do pobierania miejsc z paginacją
async function fetchPlaces(query, cities) {
  const allData = []; // Tablica na dane ze wszystkich miast

  for (const city of cities) {
    console.log(`Rozpoczynam wyszukiwanie dla miasta: ${city}`);

    let allPlaces = [];
    let nextPageToken = null;

    do {
      try {
        const response = await axios.get(TEXT_SEARCH_URL, {
          params: {
            query: `${query} ${city}`,
            key: API_KEY,
            pagetoken: nextPageToken, // Pobierz kolejną stronę wyników, jeśli dostępna
          },
        });

        if (response.status === 200) {
          const places = response.data.results;
          console.log(
            `Znaleziono ${places.length} wyników dla miasta: ${city}`
          );
          allPlaces = [...allPlaces, ...places]; // Dodaj wyniki do listy wszystkich miejsc

          // Ustaw `next_page_token` na następną stronę, jeśli istnieje
          nextPageToken = response.data.next_page_token || null;

          // API wymaga krótkiego opóźnienia przed użyciem `next_page_token`
          if (nextPageToken) {
            await new Promise((resolve) => setTimeout(resolve, 2000));
          }
        } else {
          console.error("Błąd podczas wyszukiwania miejsc:", response.status);
          break;
        }
      } catch (error) {
        console.error(
          `Wystąpił błąd podczas wyszukiwania w mieście ${city}:`,
          error.message
        );
        break;
      }
    } while (nextPageToken);

    // Pobierz szczegóły każdego miejsca
    const detailedPlaces = await Promise.all(
      allPlaces.map(async (place) => {
        const details = await fetchPlaceDetails(place.place_id);
        return {
          Miasto: city,
          Nazwa: place.name || "Brak danych",
          "Numer telefonu": details?.formatted_phone_number || "Brak danych",
          "Adres www": details?.website || "Brak danych",
          "Adres e-mail": "Brak danych", // Google Places API nie obsługuje e-maili
          "Adres (lokalizacja)": place.formatted_address || "Brak danych",
          "Kod pocztowy":
            details?.address_components?.find((comp) =>
              comp.types.includes("postal_code")
            )?.long_name || "Brak danych",
          "Link do wizytówki Google Maps": `https://www.google.com/maps/place/?q=place_id:${place.place_id}`,
        };
      })
    );

    // Dodaj szczegółowe dane do ogólnej listy
    allData.push(...detailedPlaces);
  }

  // Zapisz wszystkie dane do Excela
  saveToExcel(allData, query);
}

// Funkcja do pobierania szczegółowych danych miejsca
async function fetchPlaceDetails(placeId) {
  try {
    const response = await axios.get(DETAILS_URL, {
      params: {
        place_id: placeId,
        key: API_KEY,
        fields:
          "name,formatted_phone_number,website,formatted_address,address_components",
      },
    });

    if (response.status === 200) {
      return response.data.result;
    } else {
      console.error(
        `Błąd podczas pobierania szczegółów dla place_id ${placeId}:`,
        response.status
      );
      return null;
    }
  } catch (error) {
    console.error(
      `Błąd podczas pobierania szczegółów dla place_id ${placeId}:`,
      error.message
    );
    return null;
  }
}

// Funkcja do zapisu danych do Excela
function saveToExcel(data, query) {
  const workBook = xlsx.utils.book_new();
  const workSheet = xlsx.utils.json_to_sheet(data);
  xlsx.utils.book_append_sheet(workBook, workSheet, "Places");

  const outputFile = `places_${query.replace(
    / /g,
    "_"
  )}_${new Date().getTime()}.xlsx`;
  xlsx.writeFile(workBook, outputFile);
  console.log(`Dane zapisano do pliku ${outputFile}`);
}

// Przykładowe uruchomienie
const query = "Dom opieki"; // Wyszukiwane zapytanie
fetchPlaces(query, cities);
